### ISSUE TITLE
Bug in Product Hunt Alerts daemon

### ISSUE THREAD

**Issue by markcarey** [lucybot/datafire#2]
Claims to to match product with your query, but the PH request only send the the category constant and not the query constant.  See attached.
![datafire_-_daemon_editor](https://cloud.githubusercontent.com/assets/98136/11901711/ffc5c57c-a57a-11e5-9d6d-5f3eaddd349d.png)

Also, I did not receive any email, the email section says zero requests and zero responses, or rather both empt arrays.

**Comment by markcarey** [comment]
I see now that PH API doesn't support query, and that the Email API is doing the filtering part of it.

**Comment by rbren** [comment]
That's right. We're going to do a deeper PH integration in the future, stay tuned!
